#ifndef __LIB_FAULT_H
#define __LIB_FAULT_H

#define GENERAL_FAULT   -1
#define CANNOT_FIND_FD_IN_PROCESS_STACK -2
#define CANNOT_FIND_INODE_IN_GLOBAL_FILE_TABLE -3
#define CANNOT_READ_FILE    -4
#define CANNOT_REMOVE_SOME_COTENT_FROM_FILE -5

#endif